### PR TITLE
Update for compatibility with latest twitter-text gem

### PR DESCRIPTION
**Pull request by andreas12345**
Replace Twitter::Autolink by Twitter::TwitterText::Autolink

### CODE REVIEW

**Comment by Nakilon** [comment]
The patch should probably include the twitter's gem version stated in .gemspec

**Comment by bartkamphorst** [comment]
@Nakilon Can you expand on what is needed for this PR to be merged? Would you need an explicit version number specified in the gemspec, like `s.add_dependency 'twitter-text', '>= 2.0'` or something?

[Gollum](https://github.com/gollum/gollum/issues/1273) has fixed `twitter-text` to `1.14.7` at the moment, but ideally we would able to use the latest version of that gem.

**Comment by Nakilon** [comment]
@bartkamphorst yeah, the "update for compatibility" does not really tell the library user which version is compatible and which is not. It would be nice to have the version specified as `'twitter-text', ~> ...`

**Comment by bartkamphorst** [comment]
Thanks @Nakilon . The relevant commit is https://github.com/FalconSocial/twitter-text/commit/e304fc66c23beccf477fc8f77fbd6ba72c03e53d, where the top-level namespace was changed and the version was bumped to `v.2.1.0`.

@andreas12345 Could you modify your PR by changing [line 25 in wikicloth.gemspec](https://github.com/nricciar/wikicloth/blob/master/wikicloth.gemspec#L25) to `s.add_dependency 'twitter-text', '>= 2.1'`?

**Comment by dometto** [comment]
@nricciar would you merge a similar PR if someone reopens it with the changes suggested by @bartkamphorst and @Nakilon

**Comment by bartkamphorst** [comment]
Ping @andreas12345 .

**Comment by andreas12345** [comment]
Done!

**Comment by namiwang** [comment]
@andreas12345 Hi! Thanks for the merging, and can we also have a new version released please?

**Comment by dometto** [comment]
Ping @nricciar

**Review by nricciar — APPROVED** [review]

**Comment by dometto** [comment]
Great, thanks so much @nricciar! 🎆  Any chance you could cut a quick new release of the gem? Last version on rubygems is from 2015, I'm sure many people would appreciate a new version with the updates that have been made over the past years!

**Comment by bartkamphorst** [comment]
@nricciar Seconding the request for a new wikicloth release. Would be much appreciated!

**Comment by Nakilon** [comment]
Guys, you can specify the Github repo+branch in your Gemfile when the published gem is outdated.

**Comment by dometto** [comment]
> Just a reminder: you can specify the Github repo+branch in your Gemfile when the published gem is outdated.

Unfortunately this is not a solution for gems, since gem dependencies must be declared in a `.gemspec`, not in a `Gemfile`. Is there anyone with the ability to release a new gem version of wikicloth?

**Comment by Nakilon** [comment]
> not a solution for gems

While this is true, you can temporary provide a guide for your gem users that when they want to use yours they have to add two lines to Gemfile, not one.

**Pull request merged**
